version: '3.5'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: zabbix-grafana
    environment:
     TZ: Asia/Shanghai
    ports:
      - 3000:3000
    volumes:
      - /home/data/grafana:/var/lib/grafana
      - ./plugins:/var/lib/grafana/plugins
    restart: always